
export const normalizeTeamName = (name) => {
    if (!name) return '';
    return name.trim().toLowerCase()
        .replace(/ç/g, 'c')
        .replace(/ğ/g, 'g')
        .replace(/ı/g, 'i')
        .replace(/ö/g, 'o')
        .replace(/ş/g, 's')
        .replace(/ü/g, 'u')
        .replace(/\s+/g, '-')
        .replace(/[^a-z0-9-]/g, '');
};

const ALL_TEAM_LOGOS = [
    "1-fc-heidenheim",
    "1-fc-heidenheim-1846",
    "1-fc-koln",
    "1-fc-slovacko",
    "1-fc-tatran-preov",
    "1-fc-union-berlin",
    "1-fsv-mainz-05",
    "1-sk-prostjov",
    "aali",
    "aarhus-gf",
    "aberdeen",
    "aberdeen-fc",
    "ac-marinhense",
    "ac-milan",
    "ac-monza",
    "ac-sparta-prague",
    "ac-vila-mea",
    "academica-vitoria",
    "academico-viseu-fc",
    "academico-viseu-u23",
    "accra-hearts-of-oak",
    "accrington-stanley",
    "acf-fiorentina",
    "acsc-fc-arges",
    "ad-camacha",
    "ad-ceuta",
    "ad-jaguar",
    "ad-machico",
    "ad-os-limianos",
    "adana-demirspor",
    "adelaide-united",
    "ado-den-haag",
    "aduana-stars-fc",
    "ae-kifisias",
    "ae-larisa",
    "aek-athens",
    "aek-larnaca",
    "ael-limassol",
    "afc-ajax",
    "afc-bournemouth",
    "afc-unirea-04-slobozia",
    "afk-csikszereda-miercurea-ciuc",
    "agostini-s-cadenasso-g",
    "aik",
    "airdrieonians",
    "aj-auxerre",
    "ajax-amsterdam",
    "ajman",
    "akhmat-grozny",
    "akritas-chlorakas",
    "akron-togliatti",
    "al-ahli",
    "al-ahli-doha",
    "al-ain",
    "al-arabi-sc",
    "al-bahrain",
    "al-bataeh",
    "al-dhafra",
    "al-duhail",
    "al-ettifaq",
    "al-fateh",
    "al-fayha",
    "al-gharafa",
    "al-hazem",
    "al-hilal",
    "al-ittihad",
    "al-ittihad-kalba",
    "al-jazira",
    "al-khaldiya",
    "al-khaleej",
    "al-kholood",
    "al-najma",
    "al-najma-sc",
    "al-nasr-dubai",
    "al-nassr",
    "al-okhdood",
    "al-qadsiah",
    "al-rayyan",
    "al-riyadh",
    "al-sadd",
    "al-sailiya",
    "al-shabab",
    "al-shahaniya",
    "al-shamal-sc",
    "al-sharjah",
    "al-taawoun",
    "al-wahda-fc",
    "al-wakrah",
    "al-wasl",
    "alanyaspor",
    "albacete-balompie",
    "albirex-niigata-singapore",
    "alebrijes-de-oaxaca",
    "algeria",
    "alhama-club-de-futbol",
    "almere-city-fc",
    "almeria",
    "amed-sportif-faaliyetler",
    "amrun-spartans-fc",
    "anadia",
    "angers-sco",
    "angola",
    "anorthosis-famagusta",
    "antalyaspor",
    "aparecida-fc",
    "apo-levadiakos",
    "apoel-nicosia",
    "apoel-nikosia",
    "apollon-limassol",
    "ar-sao-martinho",
    "arbroath",
    "arda-kardzhali",
    "arema-fc",
    "arezzo",
    "argentina",
    "aris-limassol",
    "aris-thessaloniki",
    "arka-gdynia",
    "arsenal",
    "arsenal-fc",
    "as-monaco",
    "as-roma",
    "asante-kotoko-sc",
    "ascoli",
    "ashdod-sc",
    "aso-chlef",
    "associacao-naval-1893",
    "asteras-aktor",
    "aston-villa",
    "at-malveira",
    "atalanta",
    "atalanta-bc",
    "atalanta-u20",
    "atalanta-u23",
    "athletic-bilbao",
    "athletic-club",
    "atlante-fc",
    "atlas-fc",
    "atletico-de-madrid",
    "atletico-madrid",
    "atletico-san-luis",
    "atromitos-athens",
    "auckland-fc",
    "audace-cerignola",
    "australia",
    "australia-u23",
    "austria",
    "austria-vienna",
    "avs-futebol",
    "ayr-united",
    "ayutthaya-united",
    "az-alkmaar",
    "az-picerno",
    "bagnolini-d-colombo-a",
    "bala-town",
    "balestier-khalsa",
    "bali-united-fc",
    "baltika-kaliningrad",
    "bandirmaspor",
    "banik-ostrava",
    "baniyas",
    "barcelona",
    "barnet",
    "barrow-afc",
    "barry-town",
    "basake-holy-stars-fc",
    "basaksehir-fk",
    "basel",
    "bayer-04-leverkusen",
    "bayern-munich",
    "bechem-united",
    "beitar-jerusalem",
    "belgium",
    "benevento",
    "benfica",
    "benfica-castelo-branco",
    "benfica-u23",
    "benin",
    "berekum-chelsea",
    "beroe-stara-zagora",
    "besiktas-jk",
    "bg-pathum-united",
    "bhayangkara-presisi-lampung-fc",
    "bibiani-gold-stars-fc",
    "birkirkara-fc",
    "bk-hacken",
    "bnei-sakhnin",
    "bodoglimt",
    "bodrum-fk",
    "bohemians-prague-1905",
    "bologna",
    "bologna-fc-1909",
    "bologna-u20",
    "boluspor",
    "borneo-fc-samarinda",
    "borrelli-l-fermi-a",
    "borussia-dortmund",
    "borussia-mgladbach",
    "borussia-monchengladbach",
    "botev-plovdiv",
    "botev-vratsa",
    "botswana",
    "bournemouth",
    "bra",
    "brazil",
    "breidablik-kopavogur",
    "brentford",
    "brentford-fc",
    "brighton-hove-albion",
    "brisbane-roar",
    "bristol-rovers",
    "brito-sc",
    "briton-ferry-llansawel-afc",
    "bromley",
    "brondby-if",
    "bruk-bet-termalica-nieciecza",
    "brunei-dpmm-fc",
    "bryne-fk",
    "bsc-young-boys",
    "budaiya",
    "burgos-club-de-futbol",
    "buriram-united",
    "burkina-faso",
    "burnley",
    "burnley-fc",
    "ca-osasuna",
    "cabo-verde",
    "cadiz",
    "caernarfon-town",
    "cagliari",
    "cagliari-calcio",
    "cagliari-u20",
    "cambridge-united",
    "cameroon",
    "campobasso-fc",
    "canada",
    "canberra-united",
    "cancun-fc",
    "caniato-c-a-malgaroli-l",
    "cardiff-met-fc",
    "carpi",
    "casa-pia-ac",
    "casarano",
    "casertana",
    "catania",
    "catini-n-perfetti-n",
    "cavese",
    "caykur-rizespor",
    "cd-castellon",
    "cd-celoricense",
    "cd-cinfaes",
    "cd-fatima",
    "cd-gouveia",
    "cd-guadalajara",
    "cd-irapuato",
    "cd-nacional",
    "cd-ribeira-brava",
    "cd-santa-clara",
    "cd-tapatio",
    "cd-toluca",
    "cd-tondela",
    "cds-tampico-madero",
    "celta-de-vigo",
    "celta-vigo",
    "celtic",
    "celtic-fc",
    "central-coast-mariners",
    "cercle-brugge",
    "cesena-u20",
    "cf-estrela-amadora",
    "cf-marialvas",
    "cf-monterrey",
    "cf-pachuca",
    "cf-uniao-de-lamas",
    "cfr-1907-cluj",
    "cfr-cluj",
    "charlton-athletic",
    "chaves",
    "chaves-b",
    "chelsea",
    "chelsea-fc",
    "cheltenham-town",
    "cherno-more-varna",
    "chesterfield",
    "chiangrai-united",
    "china-u23",
    "chonburi-fc",
    "club-america",
    "club-atletico-de-madrid",
    "club-atletico-la-paz",
    "club-atletico-morelia",
    "club-brugge-kv",
    "club-leon",
    "club-necaxa",
    "club-puebla",
    "club-tijuana",
    "clube-nautico-capibaribe",
    "clube-oriental-de-lisboa",
    "coccioli-a-lorusso-l",
    "colacioppo-g-martin-manzano-j-c",
    "colchester-united",
    "colombia",
    "colwyn-bay",
    "comercio-e-industria",
    "como",
    "como-1907",
    "comoros",
    "connahs-quay-nomads",
    "cordoba",
    "correcaminos-uat",
    "cortimiglia-d-o-byrne-s",
    "corum-fk",
    "cosenza",
    "costa-adeje-tenerife",
    "cote-divoire",
    "cr-belouizdad",
    "cracovia",
    "crawley-town",
    "cremonese",
    "cremonese-u20",
    "crewe-alexandra",
    "croatia",
    "crotone",
    "cruz-azul",
    "crystal-palace",
    "cs-constantine",
    "cs-universitatea-craiova",
    "cska-1948",
    "cska-moscow",
    "cska-sofia",
    "cultural-leonesa",
    "curacao",
    "damac-fc",
    "damaiense",
    "de-graafschap",
    "decisao-goiana",
    "degerfors-if",
    "deportivo-alaves",
    "deportivo-la-coruna",
    "desportivo-de-moncao",
    "dewa-united-fc",
    "dibba-al-fujairah",
    "differdange-fc-03",
    "dinamo-makhachkala",
    "dinamo-minsk",
    "djurgardens-if",
    "dobrudzha-dobrich",
    "dorados-de-sinaloa",
    "dr-congo",
    "dreams",
    "dukla-praha",
    "dundee-fc",
    "dundee-united",
    "dundee-united-fc",
    "dunfermline-athletic",
    "dux-logrono",
    "dynamo-kyiv",
    "dynamo-moscow",
    "ecuador",
    "egea-f-e-paz-j-p",
    "egypt",
    "eibar",
    "eintracht-frankfurt",
    "elche",
    "elche-cf",
    "electrico-fc",
    "eleven-wonders",
    "england",
    "enosis-neon-paralimniou",
    "enosis-neon-ypsona-fc",
    "epicentr-kamyanets-podilskyi",
    "equatorial-guinea",
    "erzurumspor-fk",
    "es-ben-aknoun",
    "es-mostaganem",
    "es-setif",
    "esenler-erokspor",
    "espanyol",
    "estoril-praia-u23",
    "estrela-amadora-u23",
    "ethnikos-achnas",
    "everton",
    "everton-fc",
    "excelsior",
    "excelsior-rotterdam",
    "eyupspor",
    "falkirk",
    "falkirk-fc",
    "famalicao-u23",
    "fatih-karagumruk",
    "fc-alpendorada",
    "fc-alverca",
    "fc-alverca-b",
    "fc-andorra",
    "fc-arouca",
    "fc-ashdod",
    "fc-augsburg",
    "fc-badalona",
    "fc-banik-ostrava",
    "fc-barcelona",
    "fc-basel-1893",
    "fc-bayern-munchen",
    "fc-blau-weiss-linz",
    "fc-botosani",
    "fc-copenhagen",
    "fc-den-bosch",
    "fc-dinamo-1948",
    "fc-dordrecht",
    "fc-drita",
    "fc-eindhoven",
    "fc-emmen",
    "fc-empoli",
    "fc-famalicao",
    "fc-fredericia",
    "fc-groningen",
    "fc-hermannstadt",
    "fc-hradec-kralove",
    "fc-iberia-1999",
    "fc-juarez",
    "fc-kilmarnock",
    "fc-kobenhavn",
    "fc-kopenhagen",
    "fc-krasnodar",
    "fc-kudrivka",
    "fc-lausanne-sport",
    "fc-lorient",
    "fc-lugano",
    "fc-luzern",
    "fc-metaloglobus-bucharest",
    "fc-metz",
    "fc-midtjylland",
    "fc-milsami-orhei",
    "fc-nantes",
    "fc-noah",
    "fc-nordsjaelland",
    "fc-oleksandriya",
    "fc-pari-nizhniy-novgorod",
    "fc-porto",
    "fc-porto-b",
    "fc-prishtina",
    "fc-rapid-1923",
    "fc-rostov",
    "fc-sellier-bellot-vlaim",
    "fc-serpa",
    "fc-sion",
    "fc-slovan-liberec",
    "fc-sochi",
    "fc-spartak-trnava",
    "fc-st-gallen-1879",
    "fc-st-mirren",
    "fc-st-pauli",
    "fc-sudtirol",
    "fc-thun",
    "fc-tirsense",
    "fc-tk-1914-amorin",
    "fc-toulouse",
    "fc-twente",
    "fc-universitatea-cluj",
    "fc-utrecht",
    "fc-viktoria-plzen",
    "fc-vion-zlate-moravce",
    "fc-volendam",
    "fc-winterthur",
    "fc-zlin",
    "fc-zurich",
    "fci-levadia-tallinn",
    "fcsb",
    "fcv-dender-eh",
    "fcv-farul-constanta",
    "feirense",
    "felgueiras",
    "fenerbahce",
    "ferencvaros-tc",
    "feyenoord",
    "feyenoord-rotterdam",
    "fiorentina",
    "fiorentina-u20",
    "fk-aktobe",
    "fk-algiris",
    "fk-bodoglimt",
    "fk-budunost-podgorica",
    "fk-crvena-zvezda",
    "fk-cukaricki",
    "fk-dukla-prague",
    "fk-haugesund",
    "fk-imt-belgrad",
    "fk-jablonec",
    "fk-javor-matis-ivanjica",
    "fk-mlada-boleslav",
    "fk-mladost-lucani",
    "fk-napredak-krusevac",
    "fk-novi-pazar",
    "fk-pardubice",
    "fk-partizan",
    "fk-partizan-belgrade",
    "fk-radnicki-1923-kragujevac",
    "fk-radnicki-nis",
    "fk-radnik-surdulica",
    "fk-spartak-subotica",
    "fk-teplice",
    "fk-tsc-backa-topola",
    "fk-viktoria-ikov",
    "fk-vojvodina-novi-sad",
    "fleetwood-town",
    "flint-town-united",
    "florgrade-fc",
    "floriana-fc",
    "foggia",
    "forli",
    "fortuna-sittard",
    "france",
    "fredrikstad-fk",
    "frosinone-calcio",
    "frosinone-u20",
    "fulham",
    "fulham-fc",
    "fumagalli-f-giacomini-l",
    "futbol-club-barcelona",
    "gabon",
    "gais",
    "galatasaray",
    "gaziantep-fk",
    "gd-alcochetense",
    "gd-estoril-praia",
    "gd-lagoa",
    "gd-peniche",
    "gd-resende",
    "gd-samora-correia",
    "gd-vitoria-sernache",
    "genclerbirligi-ankara",
    "genoa",
    "genoa-cfc",
    "genoa-u20",
    "germany",
    "getafe",
    "getafe-cf",
    "geylang-international",
    "ghana",
    "gil-vicente-fc",
    "gil-vicente-u23",
    "gillingham",
    "giovannini-f-giovannini-u-m",
    "gira-united-fc",
    "girona-fc",
    "giugliano",
    "gks-katowice",
    "gnk-dinamo-zagreb",
    "go-ahead-eagles",
    "gornik-zabrze",
    "goztepe",
    "granada",
    "granada-club-de-futbol",
    "grasshopper-club-zurich",
    "grazer-ak-1902",
    "greenock-morton",
    "grimsby-town",
    "grupo-desportivo-de-braganca",
    "gubbio",
    "guidonia-montecelio-1937",
    "haiti",
    "halmstads-bk",
    "hamarkameratene",
    "hamburger-sv",
    "hammarby-if",
    "hapoel-beer-sheva",
    "hapoel-haifa",
    "hapoel-ironi-kiryat-shmona",
    "hapoel-jerusalem",
    "hapoel-petach-tikva",
    "hapoel-petah-tikva",
    "hapoel-tel-aviv",
    "harrogate-town",
    "hatayspor",
    "haverfordwest-county-afc",
    "heart-of-lions",
    "heart-of-midlothian-fc",
    "hellas-verona",
    "hellas-verona-u20",
    "helmond-sport",
    "heracles-almelo",
    "hibernian",
    "hibernian-fc",
    "hibernians",
    "hidd",
    "hk-zrinjski-mostar",
    "hnk-gorica",
    "hnk-hajduk-split",
    "hnk-rijeka",
    "hnk-vukovar-1991",
    "hohoe-united-fc",
    "hougang-united",
    "huesca",
    "if-brommapojkarna",
    "if-elfsborg",
    "ifk-goteborg",
    "ifk-norrkoping",
    "ifk-varnamo",
    "igdir-fk",
    "ihud-bnei-sakhnin",
    "ik-sirius",
    "ilves",
    "immigration-fc",
    "inter",
    "inter-club-descaldes",
    "inter-milan",
    "inter-u20",
    "iran",
    "iran-u23",
    "iraq-u23",
    "ironi-dorot-tiberias",
    "ironi-kiryat-shmona",
    "ironi-tiberias",
    "istanbulspor",
    "jagiellonia-bialystok",
    "japan",
    "japan-u23",
    "jd-lajense",
    "johor-darul-tazim",
    "jong-ajax",
    "jong-az-alkmaar",
    "jong-fc-utrecht",
    "jong-psv-eindhoven",
    "jordan",
    "jordan-u23",
    "js-kabylie",
    "js-saoura",
    "juve-stabia",
    "juventude-sport-clube",
    "juventus",
    "juventus-fc",
    "juventus-next-gen-u23",
    "juventus-u20",
    "k-slovan-bratislava",
    "kaa-gent",
    "kairat-almaty",
    "kanchanaburi-power-fc",
    "karela-united",
    "karpaty-lviv",
    "kasimpasa",
    "kayserispor",
    "keciorengucu",
    "kelantan-the-real-warriors-fc",
    "kf-egnatia",
    "kf-shkendija",
    "kfum-kameratene-oslo",
    "khor-fakkan",
    "kilmarnock-fc",
    "kocaelispor",
    "kolos-kovalivka",
    "konyaspor",
    "korona-kielce",
    "krc-genk",
    "kristiansund-bk",
    "krylya-sovetov-samara",
    "kryvbas-kryvyi-rig",
    "kuala-lumpur-city-fc",
    "kuching-city",
    "kups",
    "kv-mechelen",
    "kvc-westerlo",
    "kyrgyzstan-u23",
    "lamphun-warrior",
    "las-palmas",
    "lask",
    "latina",
    "lazio",
    "lazio-u20",
    "le-havre-ac",
    "lebanon-u23",
    "leca-fc",
    "lecce",
    "lecce-u20",
    "lech-pozna",
    "lech-poznan",
    "lechia-gdansk",
    "leeds-united",
    "leganes",
    "legia-warszawa",
    "leixoes-sc",
    "leixoes-sc-u23",
    "leones-negros",
    "levante-ud",
    "levski-sofia",
    "lgc-moncarapachense",
    "lille",
    "lincoln-red-imps",
    "linfield-fc",
    "lion-city-sailors",
    "liverpool",
    "liverpool-fc",
    "livingston",
    "livingston-fc",
    "llanelli-afc",
    "lnz-cherkasy",
    "lokomotiv-moscow",
    "lokomotiv-plovdiv",
    "lokomotiv-sofia",
    "losc-lille",
    "louletano-dc",
    "ludogorets",
    "ludogorets-razgrad",
    "lusitania-lourosa",
    "macarthur-fc",
    "maccabi-bnei-reineh",
    "maccabi-bney-reine",
    "maccabi-haifa",
    "maccabi-netanya",
    "maccabi-tel-aviv",
    "madrid-cff",
    "madura-united-fc",
    "maguary",
    "maharlika",
    "malaga",
    "mali",
    "malkiya",
    "mallorca",
    "malmo-ff",
    "malut-united-fc",
    "manchester-city",
    "manchester-united",
    "manisa-fk",
    "maritimo",
    "maritimo-u23",
    "marsaxlokk-fc",
    "mazatlan-fc",
    "mb-rouissat",
    "mc-alger",
    "mc-el-bayadh",
    "mc-oran",
    "medeama-sc",
    "melaka-fc",
    "melbourne-city",
    "melbourne-victory",
    "metalist-1925-kharkiv",
    "mexico",
    "mfk-chrudim",
    "mfk-karvina",
    "mfk-skalica",
    "milan",
    "milan-u20",
    "milton-keynes-dons",
    "mineros-de-zacatecas",
    "mirandes",
    "mjallby-aif",
    "mlada-boleslav",
    "molde-fk",
    "monopoli",
    "montana",
    "monza-u20",
    "moreirense-fc",
    "morocco",
    "mortagua",
    "mosta-fc",
    "motherwell-fc",
    "motor-lublin",
    "mozambique",
    "muang-thong-united",
    "muharraq",
    "mvv-maastricht",
    "nac-breda",
    "nakhon-ratchasima-mazda-fc",
    "napoli",
    "napoli-u20",
    "nations-fc",
    "naxxar-lions-fc",
    "nec-nijmegen",
    "negeri-sembilan",
    "neom-sc",
    "netherlands",
    "new-zealand",
    "newcastle-jets",
    "newcastle-united",
    "newport-county",
    "nice",
    "nigeria",
    "nk-celje",
    "nk-istra-1961",
    "nk-lokomotiva-zagreb",
    "nk-olimpija-ljubljana",
    "nk-osijek",
    "nk-varazdin",
    "nk-veres-rivne",
    "norway",
    "nottingham-forest",
    "notts-county",
    "o-elvas-cad",
    "obolon-kyiv",
    "odense-boldklub",
    "ofi-crete-fc",
    "ofk-beograd",
    "ofk-dynamo-malenice",
    "ogc-nice",
    "oldham-athletic",
    "oliveira-hospital",
    "olympiacos-fc",
    "olympiacos-piraeus",
    "olympiakos-nicosia",
    "olympique-akbou",
    "olympique-de-marseille",
    "olympique-lyon",
    "olympique-lyonnais",
    "olympique-marseille",
    "omonia-aradippou",
    "omonia-nicosia",
    "osasuna",
    "osters-if",
    "oud-heverlee-leuven",
    "pacos-de-ferreira",
    "pafos-fc",
    "paksi-fc",
    "panama",
    "panathinaikos",
    "panathinaikos-fc",
    "panetolikos-gfs",
    "panserraikos",
    "paok",
    "paok-thessaloniki",
    "paphos-fc",
    "paradou-ac",
    "paraguay",
    "paris-fc",
    "paris-saint-germain",
    "parma",
    "parma-calcio-1913",
    "parma-u20",
    "partick-thistle",
    "pdrm-fc",
    "pec-zwolle",
    "penafiel",
    "penang",
    "pendikspor",
    "penybont",
    "perego-g-potenza-l",
    "persebaya-surabaya",
    "persib-bandung",
    "persija-jakarta",
    "persijap-jepara",
    "persik-kediri",
    "persis-solo",
    "persita-tangerang",
    "perth-glory",
    "perugia",
    "petrolul-ploiesti",
    "pianese",
    "piast-gliwice",
    "pineto",
    "pisa",
    "pisa-l-villa-r",
    "pisa-sporting-club",
    "pogon-szczecin",
    "polissya-zhytomyr",
    "pontedera",
    "port-fc",
    "portimonense-sad",
    "portimonense-sporting-clube",
    "portimonense-u23",
    "portugal",
    "potenza-calcio",
    "psbs-biak",
    "psim-yogyakarta",
    "psm-makassar",
    "psv-eindhoven",
    "pt-prachuap-fc",
    "pumas-unam",
    "qarabag-fk",
    "qatar",
    "qatar-sc",
    "qatar-u23",
    "queens-park-fc",
    "queretaro-fc",
    "raal-la-louviere",
    "racing-power-football-club",
    "radomiak-radom",
    "raith-rovers",
    "rakow-czestochowa",
    "randers-fc",
    "rangers",
    "rangers-fc",
    "rapid-vienna",
    "ratchaburi",
    "ravenna",
    "rayo-vallecano",
    "rayong-fc",
    "rb-leipzig",
    "rc-lens",
    "rc-strasbourg-alsace",
    "rcd-espanyol-barcelona",
    "rcd-espanyol-de-barcelona",
    "rcd-mallorca",
    "real-betis",
    "real-betis-balompie",
    "real-club-deportivo-de-la-coruna",
    "real-madrid",
    "real-oviedo",
    "real-racing-club",
    "real-sociedad",
    "real-sociedad-b-u21",
    "real-valladolid",
    "real-zaragoza",
    "rebordosa-ac",
    "red-bull-salzburg",
    "red-star-belgrade",
    "retro",
    "rfs",
    "riffa",
    "rio-ave-fc",
    "rio-ave-u23",
    "rkc-waalwijk",
    "roda-jc-kerkrade",
    "roma",
    "roma-u20",
    "rosenborg-bk",
    "ross-county",
    "royal-antwerp-fc",
    "royal-charleroi-sc",
    "royale-union-saint-gilloise",
    "rsc-anderlecht",
    "rubin-kazan",
    "rukh-lviv",
    "sabah-fc",
    "sabah-fk",
    "sakaryaspor",
    "salernitana",
    "salford-city",
    "samartex",
    "sambenedettese",
    "samsunspor",
    "sandefjord-fotball",
    "santa-clara-u23",
    "santa-cruz",
    "santos-laguna",
    "sariyer",
    "sarpsborg-08-ff",
    "sassuolo",
    "sassuolo-u20",
    "saudi-arabia",
    "saudi-arabia-u23",
    "sc-beira-mar",
    "sc-braga",
    "sc-braga-u23",
    "sc-cambuur",
    "sc-farense",
    "sc-farense-u23",
    "sc-freiburg",
    "sc-heerenveen",
    "sc-lusitania",
    "sc-mirandela",
    "sc-otelul-galati",
    "sc-poltava",
    "sc-telstar",
    "sc-vianense",
    "sc-vila-real",
    "scotland",
    "scr-altach",
    "scu-torreense",
    "sd-eibar",
    "selangor-football-club",
    "semen-padang-fc",
    "senegal",
    "septemvri-sofia",
    "serikspor-as",
    "servette-fc",
    "servette-genf",
    "sevilla",
    "sevilla-fc",
    "shabab-al-ahli-dubai",
    "shakhtar-donetsk",
    "shelbourne",
    "sheriff-tiraspol",
    "shrewsbury-town",
    "silkeborg-if",
    "sint-truidense-vv",
    "siracusa-calcio",
    "sitra",
    "sivasspor",
    "sk-brann",
    "sk-hanacka-slavia-kromi",
    "sk-sigma-olomouc",
    "sk-slavia-prague",
    "sk-slavia-praha",
    "sk-sturm-graz",
    "sl-benfica",
    "sl-benfica-b-u21",
    "slaven-belupo-koprivnica",
    "slavia-sofia",
    "sliema-wanderers",
    "sonderjyske",
    "sorrento",
    "south-africa",
    "south-korea",
    "south-korea-u23",
    "spadola-a-vavassori-m",
    "spain",
    "sparta-rotterdam",
    "spartak-moscow",
    "spartak-varna",
    "spezia-calcio",
    "sport-comercio-e-salgueiros",
    "sport-recife",
    "sporting-braga",
    "sporting-cp",
    "sporting-cp-b-u21",
    "sporting-gijon",
    "sporting-u23",
    "ss-lazio",
    "ss-virtus",
    "ssc-bari",
    "ssc-napoli",
    "st-johnstone",
    "st-mirren-fc",
    "stade-brestois-29",
    "stade-rennais-fc",
    "stallion",
    "standard-liege",
    "stoke-city",
    "stromsgodset-if",
    "su-sintrense",
    "sudan",
    "sukhothai",
    "sunderland",
    "sunderland-afc",
    "sv-ried",
    "sv-werder-bremen",
    "swedru-all-blacks-united-fc",
    "swindon-town",
    "switzerland",
    "sydney-fc",
    "syria-u23",
    "tampines-rovers",
    "tanjong-pagar-united",
    "tanzania",
    "tarxien-rainbows-fc",
    "team-altamura",
    "tepatitlan-fc",
    "terengganu",
    "ternana",
    "thailand-u23",
    "the-new-saints",
    "tigres-uanl",
    "tlaxcala-fc",
    "top-oss",
    "torino",
    "torino-fc",
    "torino-u20",
    "torpedo-moscow",
    "torreense",
    "torreense-u23",
    "torres",
    "tottenham-hotspur",
    "trabzonspor",
    "tranmere-rovers",
    "trapani",
    "tromso-il",
    "true-bangkok-united",
    "tsg-1899-hoffenheim",
    "tsg-hoffenheim",
    "tsv-hartberg",
    "tunisia",
    "twente-enschede-fc",
    "ud-leiria-u23",
    "ud-oliveirense",
    "udinese",
    "udinese-calcio",
    "uganda",
    "umm-salal-sc",
    "umraniyespor",
    "uniao-de-leiria",
    "uniao-desportiva-da-serra",
    "union-saint-gilloise",
    "united-arab-emirates-u23",
    "uruguay",
    "us-avellino",
    "us-cremonese",
    "us-lecce",
    "us-livorno-1915",
    "us-sassuolo",
    "usa",
    "usm-alger",
    "usm-khenchela",
    "uta-arad",
    "uthai-thani-fc",
    "uzbekistan",
    "uzbekistan-u23",
    "valadares-gaia",
    "valencia",
    "valencia-cf",
    "valerenga-fotball-elite",
    "valletta-fc",
    "vanspor-fk",
    "vasco-da-gama-vidigueira",
    "vejle-boldklub",
    "venados",
    "vfb-stuttgart",
    "vfl-wolfsburg",
    "viborg-ff",
    "vietnam-u23",
    "viking-fk",
    "vikingur-gota",
    "viktoria-plze",
    "vilaverdense-fc",
    "villarreal",
    "villarreal-cf",
    "vis-pesaro",
    "vision-fc",
    "vitesse",
    "vitoria-guimaraes-sc",
    "vitoria-sc",
    "vizela",
    "vizela-u23",
    "volos-nps",
    "vvv-venlo",
    "walsall",
    "wellington-phoenix",
    "west-ham-united",
    "western-sydney-wanderers",
    "widzew-lodz",
    "willem-ii-tilburg",
    "wisla-plock",
    "wolfsberger-ac",
    "wolverhampton",
    "wolverhampton-wanderers",
    "wsg-tirol",
    "young-apostles-fc",
    "young-boys",
    "young-lions",
    "zabbar-saint-patrick-fc",
    "zaglebie-lubin",
    "zambia",
    "zeleznicar-pancevo",
    "zenit-st-petersburg",
    "zimbabwe",
    "zorya-lugansk",
    "zulte-waregem"
];

// Akıllı kısaltma açma: "B.Dortmund" -> "dortmund", "M.Gladbach" -> "gladbach", "W.Bremen" -> "bremen"
const expandAbbreviation = (name) => {
    if (!name) return name;
    // "X." veya "X. " ile başlayan kısaltmaları kaldır (tek harf + nokta)
    let expanded = name.replace(/^[A-Za-z]\.\s*/g, '').trim();
    // "XX." ile başlayan kısaltmaları da kaldır (iki harf + nokta)
    expanded = expanded.replace(/^[A-Za-z]{1,3}\.\s*/g, '').trim();
    return expanded;
};

// Levenshtein mesafesi - iki string arası benzerlik
const levenshtein = (a, b) => {
    const matrix = Array.from({ length: a.length + 1 }, (_, i) =>
        Array.from({ length: b.length + 1 }, (_, j) => (i === 0 ? j : j === 0 ? i : 0))
    );
    for (let i = 1; i <= a.length; i++) {
        for (let j = 1; j <= b.length; j++) {
            matrix[i][j] = a[i - 1] === b[j - 1]
                ? matrix[i - 1][j - 1]
                : 1 + Math.min(matrix[i - 1][j], matrix[i][j - 1], matrix[i - 1][j - 1]);
        }
    }
    return matrix[a.length][b.length];
};

export const getTeamLogo = (teamName) => {
    if (!teamName || typeof teamName !== 'string') return '/logos/default-team-logo.png';

    const lowerName = teamName.trim().toLowerCase();

    // Kısaltma açılmış versiyonları da dene
    const expandedName = expandAbbreviation(lowerName);
    const expandedNorm = normalizeTeamName(expandAbbreviation(teamName));

    // YAYGIN KISALTMALAR VE OZEL DURUMLAR
    const specialCases = {
        'b.dortmund': 'borussia-dortmund', 'b. dortmund': 'borussia-dortmund', 'bor. dortmund': 'borussia-dortmund',
        'b.mgladbach': 'borussia-mgladbach', 'b. mgladbach': 'borussia-mgladbach', 'b.m.gladbach': 'borussia-mgladbach', 'bor. mgladbach': 'borussia-mgladbach', 'bor. mönchengladbach': 'borussia-mgladbach',
        'w.bremen': 'sv-werder-bremen', 'w. bremen': 'sv-werder-bremen', 'werder bremen': 'sv-werder-bremen', 'werder': 'sv-werder-bremen',
        'e.frankfurt': 'eintracht-frankfurt', 'e. frankfurt': 'eintracht-frankfurt', 'eintr. frankfurt': 'eintracht-frankfurt',
        'h.berlin': 'hertha-bsc', 'hertha berlin': 'hertha-bsc', 'hertha bsc': 'hertha-bsc', 'hertha': 'hertha-bsc',
        'arm.bielefeld': 'arminia-bielefeld', 'arminia bielefeld': 'arminia-bielefeld',
        'gr.furth': 'spvgg-greuther-furth', 'greuther furth': 'spvgg-greuther-furth', 'greuther fürth': 'spvgg-greuther-furth',
        'sc paderborn': 'sc-paderborn-07', 'paderborn': 'sc-paderborn-07',
        'f.dusseldorf': 'fortuna-dusseldorf', 'fortuna düsseldorf': 'fortuna-dusseldorf', 'düsseldorf': 'fortuna-dusseldorf', 'dusseldorf': 'fortuna-dusseldorf',
        'h.kiel': 'holstein-kiel', 'holstein kiel': 'holstein-kiel',
        'braunschweig': 'eintracht-braunschweig', 'e.braunschweig': 'eintracht-braunschweig',
        'st.pauli': 'fc-st-pauli', 'st. pauli': 'fc-st-pauli', 'fc st. pauli': 'fc-st-pauli',
        'heidenheim': '1-fc-heidenheim', '1.fc heidenheim': '1-fc-heidenheim',
        'darmstadt': 'sv-darmstadt-98', 'darmstadt 98': 'sv-darmstadt-98',
        'nurnberg': '1-fc-nurnberg', 'nürnberg': '1-fc-nurnberg', '1.fc nürnberg': '1-fc-nurnberg',
        'k.lautern': '1-fc-kaiserslautern', 'kaiserslautern': '1-fc-kaiserslautern',
        'hannover': 'hannover-96', 'hannover 96': 'hannover-96',
        'schalke': 'fc-schalke-04', 'schalke 04': 'fc-schalke-04',
        'b.leverkusen': 'bayer-04-leverkusen', 'b leverkusen': 'bayer-04-leverkusen', 'bayer leverkusen': 'bayer-04-leverkusen', 'leverkusen': 'bayer-04-leverkusen',
        'fc koln': '1-fc-koln', 'fc köln': '1-fc-koln', 'koln': '1-fc-koln', 'köln': '1-fc-koln', '1. fc koln': '1-fc-koln',
        'sc freiburg': 'sc-freiburg', 'freiburg': 'sc-freiburg', 'vfb stuttgart': 'vfb-stuttgart', 'stuttgart': 'vfb-stuttgart',
        'hamburger sv': 'hamburger-sv', 'hsv': 'hamburger-sv', 'hamburg': 'hamburger-sv',
        'bayern': 'fc-bayern-munchen', 'bayern munchen': 'fc-bayern-munchen', 'bayern munich': 'fc-bayern-munchen',
        'dortmund': 'borussia-dortmund', 'bvb': 'borussia-dortmund', 'mgladbach': 'borussia-mgladbach', 'gladbach': 'borussia-mgladbach',
        'rb leipzig': 'rb-leipzig', 'leipzig': 'rb-leipzig', 'frankfurt': 'eintracht-frankfurt', 'wolfsburg': 'vfl-wolfsburg',
        'hoffenheim': 'tsg-hoffenheim', 'augsburg': 'fc-augsburg', 'union berlin': '1-fc-union-berlin', 'mainz': '1-fsv-mainz-05',
        'man city': 'manchester-city', 'man. city': 'manchester-city', 'man utd': 'manchester-united', 'man united': 'manchester-united', 'man. united': 'manchester-united',
        'liverpool': 'liverpool', 'chelsea': 'chelsea', 'arsenal': 'arsenal', 'tottenham': 'tottenham-hotspur', 'spurs': 'tottenham-hotspur',
        'newcastle': 'newcastle-united', 'west ham': 'west-ham-united', 'brighton': 'brighton-hove-albion', 'everton': 'everton',
        'aston villa': 'aston-villa', 'villa': 'aston-villa', 'wolves': 'wolverhampton', 'crystal palace': 'crystal-palace', 'palace': 'crystal-palace',
        'bournemouth': 'bournemouth', 'fulham': 'fulham', 'brentford': 'brentford', 'nottm forest': 'nottingham-forest', 'nottingham': 'nottingham-forest', 'not. forest': 'nottingham-forest',
        'real madrid': 'real-madrid', 'madrid': 'real-madrid', 'barcelona': 'barcelona', 'barca': 'barcelona', 'fcb': 'barcelona',
        'atletico': 'atletico-madrid', 'atletico madrid': 'atletico-madrid', 'atl madrid': 'atletico-madrid',
        'sevilla': 'sevilla', 'valencia': 'valencia', 'villarreal': 'villarreal', 'athletic': 'athletic-club', 'athletic bilbao': 'athletic-club',
        'real sociedad': 'real-sociedad', 'sociedad': 'real-sociedad', 'betis': 'real-betis', 'real betis': 'real-betis',
        'celta': 'celta-vigo', 'celta vigo': 'celta-vigo', 'getafe': 'getafe', 'osasuna': 'osasuna', 'espanyol': 'espanyol',
        'mallorca': 'mallorca', 'cadiz': 'cadiz', 'almeria': 'almeria', 'girona': 'girona-fc', 'las palmas': 'las-palmas',
        'alaves': 'deportivo-alaves', 'rayo': 'rayo-vallecano', 'rayo vallecano': 'rayo-vallecano',
        'inter': 'inter', 'inter milan': 'inter', 'milan': 'milan', 'ac milan': 'milan', 'juventus': 'juventus', 'juve': 'juventus',
        'roma': 'roma', 'as roma': 'roma', 'napoli': 'napoli', 'lazio': 'lazio', 'atalanta': 'atalanta', 'fiorentina': 'fiorentina',
        'torino': 'torino', 'bologna': 'bologna', 'udinese': 'udinese', 'sassuolo': 'sassuolo', 'verona': 'hellas-verona', 'hellas verona': 'hellas-verona',
        'genoa': 'genoa', 'lecce': 'lecce', 'monza': 'monza', 'cagliari': 'cagliari', 'südtirol': 'and-sudtirol', 'bari': 'bari', 'spezia': 'spezia', 'empoli': 'empoli', 'frosinone': 'frosinone', 'juve stabia': 'juve-stabia',
        'galatasaray': 'galatasaray', 'gs': 'galatasaray', 'fenerbahce': 'fenerbahce', 'fb': 'fenerbahce',
        'besiktas': 'besiktas-jk', 'bjk': 'besiktas-jk', 'trabzonspor': 'trabzonspor', 'ts': 'trabzonspor',
        'basaksehir': 'basaksehir', 'istanbul basaksehir': 'basaksehir', 'sivasspor': 'sivasspor', 'adana demirspor': 'adana-demirspor',
        'hatayspor': 'hatayspor', 'samsunspor': 'samsunspor', 'bodrum fk': 'bodrum-fk', 'pendikspor': 'pendikspor',
        'psg': 'paris-saint-germain', 'paris sg': 'paris-saint-germain', 'paris': 'paris-saint-germain', 'paris fc': 'psg-paris-fc',
        'marseille': 'olympique-de-marseille', 'om': 'olympique-de-marseille', 'lyon': 'olympique-lyonnais', 'ol': 'olympique-lyonnais',
        'monaco': 'as-monaco', 'lille': 'lille', 'nice': 'nice', 'lens': 'lens', 'rennes': 'rennes',
        'cc mariners': 'central-coast-mariners', 'cc-mariners': 'central-coast-mariners', 'central coast': 'central-coast-mariners',
        'perth glory': 'perth-glory', 'perth': 'perth-glory', 'sydney fc': 'sydney-fc', 'sydney': 'sydney-fc',
        'melbourne city': 'melbourne-city', 'melbourne victory': 'melbourne-victory', 'western sydney': 'western-sydney-wanderers',
        'adelaide': 'adelaide-united', 'adelaide united': 'adelaide-united', 'brisbane': 'brisbane-roar', 'brisbane roar': 'brisbane-roar',
        'celtic': 'celtic', 'rangers': 'rangers', 'aberdeen': 'aberdeen', 'hearts': 'hearts', 'hibernian': 'hibernian', 'hibs': 'hibernian',
        'dundee utd': 'dundee-united', 'dundee united': 'dundee-united', 'dundee utd.': 'dundee-united', 'st johnstone': 'st-johnstone', 'st. johnstone': 'st-johnstone', 'kilmarnock': 'kilmarnock-fc', 'st mirren': 'st-mirren', 'livingston': 'livingston-fc', 'falkirk': 'falkirk-fc',
        'porto': 'fc-porto', 'fc porto': 'fc-porto', 'benfica': 'benfica', 'sl benfica': 'benfica', 'sporting': 'sporting-cp', 'sporting cp': 'sporting-cp', 'sporting lisbon': 'sporting-cp', 'braga': 'sporting-braga', 'sporting braga': 'sporting-braga',
        'ajax': 'afc-ajax', 'psv': 'psv-eindhoven', 'psv eindhoven': 'psv-eindhoven', 'feyenoord': 'feyenoord', 'az': 'az-alkmaar', 'az alkmaar': 'az-alkmaar', 'twente': 'fc-twente', 'fc twente': 'fc-twente', 'utrecht': 'fc-utrecht', 'fc utrecht': 'fc-utrecht', 'nec nijmegen': 'nec-nijmegen', 'go ahead': 'go-ahead-eagles', 'heerenveen': 'sc-heerenveen',
        'lugano': 'fc-lugano', 'servette': 'servette-fc', 'st gallen': 'fc-st-gallen', 'st. gallen': 'fc-st-gallen', 'young boys': 'young-boys', 'zurich': 'fc-zurich', 'zürih': 'fc-zurich', 'winterthur': 'fc-winterthur',
        'charlton': 'charlton-athletic', 'stoke city': 'stoke-city', 'avellino': 'us-avellino',
        'gangwon': 'gangwon-fc', 'ulsan': 'ulsan-hyundai', 'ulsan hora': 'ulsan-hyundai', 'shanghai port': 'shanghai-port-fc', 'ratchaburi': 'ratchaburi-mitr-phol', 'persib bandung': 'persib-bandung', 'arkadag': 'arkadag-fk', 'al nassr': 'al-nassr', 'al ahli': 'al-ahli', 'al ahli doha': 'al-ahli-doha',
        'oh leuven': 'oud-heverlee-leuven', 'oud-heverlee leuven': 'oud-heverlee-leuven', 'oh leuven f': 'oud-heverlee-leuven', 'walsall': 'walsall',
        'rsc charleroi': 'royal-charleroi-sc', 'charleroi': 'royal-charleroi-sc',
        'brighton & hove albion': 'brighton-hove-albion', 'brighton hove albion': 'brighton-hove-albion', 'brighton & hove': 'brighton-hove-albion',
        'fc kopenhagen': 'fc-copenhagen', 'kopenhagen': 'fc-copenhagen', 'copenhagen': 'fc-copenhagen',
        'fc paris f': 'paris-saint-germain', 'paris f': 'paris-saint-germain',
        'real madrid f': 'real-madrid', 'fc arsenal f': 'arsenal',
        'fc liverpool': 'liverpool', 'fc burnley': 'burnley-fc', 'fc fulham': 'fulham', 'fc bologna': 'bologna',
        'fc empoli': 'empoli', 'fc kilmarnock': 'kilmarnock-fc', 'fc st. mirren': 'st-mirren-fc',
        'fc st. gallen': 'fc-st-gallen-1879', 'fc sudtirol': 'fc-sudtirol', 'fc zurich': 'fc-zurich',
        'fc winterthur': 'fc-winterthur',
        'bayern munchen': 'fc-bayern-munchen', 'bayern münchen': 'fc-bayern-munchen',
        'lazio rom': 'lazio', 'servette genf': 'servette-genf',
        'young boys bern': 'bsc-young-boys', 'bsc young boys': 'bsc-young-boys',
        'glasgow rangers': 'rangers-fc', 'celtic glasgow': 'celtic-fc',
        'fc aberdeen': 'aberdeen-fc', 'apoel nikosia': 'apoel-nikosia', 'apoel': 'apoel-nikosia',
        'motherwell': 'motherwell-fc', 'motherwell fc': 'motherwell-fc',
        'dundee fc': 'dundee-fc', 'dundee': 'dundee-fc',
        'ac monza': 'ac-monza', 'ssc bari': 'ssc-bari',
        'frosinone calcio': 'frosinone-calcio', 'spezia calcio': 'spezia-calcio',
        'paphos fc': 'paphos-fc', 'paphos': 'paphos-fc',
        'viborg ff': 'viborg-ff', 'viborg': 'viborg-ff',
        'union saint-gilloise': 'union-saint-gilloise', 'union st-gilloise': 'union-saint-gilloise',
        'standard liege': 'standard-liege', 'standard liège': 'standard-liege',
        'brighton & hove albion': 'brighton-hove-albion', 'brighton &amp; hove albion': 'brighton-hove-albion',
        'spvgg greuther fürth': 'spvgg-greuther-furth', 'spvgg greuther furth': 'spvgg-greuther-furth', 'greuther fürth': 'spvgg-greuther-furth',
        'fortuna düsseldorf': 'fortuna-dusseldorf', 'fortuna dusseldorf': 'fortuna-dusseldorf',
        'preußen münster': 'preussen-munster', 'preussen munster': 'preussen-munster',
        'sønderjyske fodbold': 'sonderjyske-fodbold', 'sonderjyske fodbold': 'sonderjyske-fodbold',
        'västerås sk': 'vasteras-sk', 'vasteras sk': 'vasteras-sk',
        'djurgårdens if dff': 'djurgardens-if-dff', 'djurgardens if dff': 'djurgardens-if-dff',
        'piteå if': 'pitea-if', 'pitea if': 'pitea-if',
        'gençlerbirliği': 'genclerbirligi',
        'atlético madrid': 'atletico-madrid', 'atletico de madrid': 'atletico-madrid',
        'deportivo alavés': 'deportivo-alaves', 'deportivo alaves': 'deportivo-alaves', 'alaves': 'deportivo-alaves',
        'brøndby if': 'brondby-if', 'brondby if': 'brondby-if',
        'fc nordsjælland': 'fc-nordsjaelland', 'fc nordsjaelland': 'fc-nordsjaelland', 'nordsjaelland': 'fc-nordsjaelland',
        'fc københavn': 'fc-kobenhavn', 'fc kobenhavn': 'fc-kobenhavn',
        'mjällby aif': 'mjallby-aif', 'bk häcken': 'bk-hacken',
        'união de leiria': 'uniao-de-leiria', 'uniao de leiria': 'uniao-de-leiria',
        'leixões sc': 'leixoes-sc', 'leixoes sc': 'leixoes-sc',
        'sg dynamo dresden': 'sg-dynamo-dresden', 'dynamo dresden': 'sg-dynamo-dresden',
        '1. fc magdeburg': '1-fc-magdeburg', 'magdeburg': '1-fc-magdeburg',
        'sc paderborn 07': 'sc-paderborn-07', 'paderborn': 'sc-paderborn-07',
        'sv 07 elversberg': 'sv-07-elversberg', 'elversberg': 'sv-07-elversberg',
        'darmstadt 98': 'darmstadt-98', 'sv darmstadt 98': 'darmstadt-98',
        'arminia bielefeld': 'arminia-bielefeld', 'a. bielefeld': 'arminia-bielefeld',
        'hertha bsc': 'hertha-bsc', 'hertha': 'hertha-bsc',
        'holstein kiel': 'holstein-kiel', 'h. kiel': 'holstein-kiel',
        'fc schalke 04': 'fc-schalke-04', 'schalke': 'fc-schalke-04', 'schalke 04': 'fc-schalke-04',
        'eintracht braunschweig': 'eintracht-braunschweig',
        'hannover 96': 'hannover-96', 'hannover': 'hannover-96',
        '1. fc nürnberg': '1-fc-nurnberg', 'nürnberg': '1-fc-nurnberg', 'nurnberg': '1-fc-nurnberg',
        'karlsruher sc': 'karlsruher-sc', 'karlsruher': 'karlsruher-sc',
        'vfl bochum 1848': 'vfl-bochum-1848', 'bochum': 'vfl-bochum-1848',
        '1. fc kaiserslautern': '1-fc-kaiserslautern',
        'fk austria wien': 'fk-austria-wien', 'austria wien': 'fk-austria-wien',
        'sk rapid wien': 'sk-rapid-wien', 'rapid wien': 'sk-rapid-wien',
        'bayer leverkusen': 'bayer-leverkusen'
    };

    // specialCases'te ara - orijinal, expanded ve nokta temizlenmiş versiyonlarla
    const namesToTry = [lowerName, expandedName, lowerName.replace(/\./g, ' ').replace(/\s+/g, ' ').trim()];
    for (const n of namesToTry) {
        if (specialCases[n]) return `/logos/${specialCases[n]}.png`;
    }

    // FC/FK/SC prefix ve F/FC suffix temizle, tekrar specialCases'e bak
    const stripped = lowerName
        .replace(/^(fc |fk |sc |cf |afc |rsc |ssc |us |rb )/, '')
        .replace(/ (f|fc|fk|sc|cf)$/, '')
        .trim();
    if (stripped !== lowerName && specialCases[stripped]) {
        return `/logos/${specialCases[stripped]}.png`;
    }

    // Expanded name'i de stripped olarak dene
    const expandedStripped = expandedName
        .replace(/^(fc |fk |sc |cf |afc |rsc |ssc |us |rb )/, '')
        .replace(/ (f|fc|fk|sc|cf)$/, '')
        .trim();
    if (expandedStripped !== expandedName && specialCases[expandedStripped]) {
        return `/logos/${specialCases[expandedStripped]}.png`;
    }

    try {
        // 1. TAM ESLESME
        const exactMatch = lowerName.replace(/\s+/g, '-').replace(/\./g, '').replace(/'/g, '');
        if (ALL_TEAM_LOGOS.includes(exactMatch)) return `/logos/${exactMatch}.png`;

        // 1.5 TAM ESLESME - Expanded versiyonla
        const expandedExact = expandedName.replace(/\s+/g, '-').replace(/\./g, '').replace(/'/g, '');
        if (expandedExact !== exactMatch && ALL_TEAM_LOGOS.includes(expandedExact)) return `/logos/${expandedExact}.png`;

        // 2. NORMALIZE EDILMIS TAM ESLESME
        const normalized = normalizeTeamName(teamName);
        if (ALL_TEAM_LOGOS.includes(normalized)) return `/logos/${normalized}.png`;

        // 2.2 EXPANDED NORMALIZE ESLESME
        if (expandedNorm !== normalized && ALL_TEAM_LOGOS.includes(expandedNorm)) return `/logos/${expandedNorm}.png`;

        // 2.5 STRIPPED ESLESME (FC/FK prefix/suffix kaldırılmış)
        const strippedNorm = normalizeTeamName(stripped);
        if (strippedNorm !== normalized && ALL_TEAM_LOGOS.includes(strippedNorm)) return `/logos/${strippedNorm}.png`;

        // 3. KISMI ESLESME (Logo icinde geciyorsa)
        const allNormalized = [normalized, expandedNorm, strippedNorm].filter((v, i, a) => v.length > 3 && a.indexOf(v) === i);
        for (const norm of allNormalized) {
            const partialMatch = ALL_TEAM_LOGOS.find(logo => logo.includes(norm));
            if (partialMatch) return `/logos/${partialMatch}.png`;
        }

        // 4. TERSTEN KISMI ESLESME (Normalized logo icinde geciyorsa)
        for (const norm of allNormalized) {
            const reverseMatch = ALL_TEAM_LOGOS.find(logo => norm.includes(logo) && logo.length > 3);
            if (reverseMatch) return `/logos/${reverseMatch}.png`;
        }

        // 5. AKILLI KELIME ESLESME (Kelime bazli - tüm versiyonlar)
        const allWords = [...new Set([
            ...normalized.split('-').filter(w => w.length > 2),
            ...expandedNorm.split('-').filter(w => w.length > 2)
        ])];
        if (allWords.length > 0) {
            // Tek kelimelik takım isimleri için özel: tam kelime eşleşmesi
            for (const logo of ALL_TEAM_LOGOS) {
                const logoWords = logo.split('-');

                // Tek kelime - ana kelime logo'nun herhangi bir kelimesiyle tam eşleşiyor mu
                if (allWords.length === 1) {
                    if (logoWords.includes(allWords[0])) return `/logos/${logo}.png`;
                }

                let matchCount = 0;
                for (const word of allWords) {
                    if (logoWords.includes(word)) matchCount++;
                }
                if (matchCount >= 2) return `/logos/${logo}.png`;
            }
        }

        // 6. BULANIK ESLESME (Levenshtein mesafesi - son çare)
        // Sadece kelime bazında, mesafe <= 1 ve kelime en az 5 karakter
        for (const norm of allNormalized) {
            if (norm.length >= 5) {
                const normWords = norm.split('-').filter(w => w.length >= 5);
                for (const logo of ALL_TEAM_LOGOS) {
                    const logoWords = logo.split('-');
                    for (const lw of logoWords) {
                        if (lw.length >= 5) {
                            for (const nw of normWords) {
                                const wd = levenshtein(nw, lw);
                                if (wd <= 1) {
                                    return `/logos/${logo}.png`;
                                }
                            }
                        }
                    }
                }
            }
        }
    } catch (e) {
        console.error('Logo matching error:', e);
    }

    // Eşleşme bulunamadı - onError tetiklensin ki TheSportsDB API deneyebilsin
    // Normalize edilmiş isimle sahte path döndür, bu yüklenemeyecek ve handleLogoError'ı tetikleyecek
    const safeNorm = normalizeTeamName(teamName) || 'unknown';
    return `/logos/nofound_${safeNorm}.png`;
};

const _showLogoInitials = (img, teamName) => {
    if (!img.parentNode) return;
    const words = teamName.trim().split(/\s+/);
    const initials = words.length === 1
        ? words[0].substring(0, 2).toUpperCase()
        : words.slice(0, 2).map(w => w[0]).join('').toUpperCase();

    const fallback = document.createElement('div');
    fallback.textContent = initials;
    fallback.title = teamName;
    fallback.style.cssText = `
        display: flex;
        align-items: center;
        justify-content: center;
        width: ${img.style.width || '70px'};
        height: ${img.style.height || '70px'};
        background: linear-gradient(135deg, #006A4E, #004d3a);
        border-radius: 50%;
        color: #FDB913;
        font-weight: 800;
        font-size: 1.3rem;
        text-shadow: 0 2px 4px rgba(0,0,0,0.4);
        box-shadow: 0 4px 15px rgba(0,0,0,0.4);
        border: 2px solid #FDB913;
        letter-spacing: 1px;
    `;
    img.parentNode.replaceChild(fallback, img);
};

// Sayfa genelinde cache - aynı takım için API'yi tekrar çağırmaz
const _logoCache = {};

export const handleLogoError = (e) => {
    const img = e.target;
    const teamName = img.alt || 'Team';
    _showLogoInitials(img, teamName);
};

export const LEAGUE_LOGOS = {
    'Serie A': 'https://i.ibb.co/N6N4CGn5/Whats-App-mage-2025-12-05-at-14-21-54-1.jpg',
    'Premier Lig': 'https://i.ibb.co/cXt6fJdd/Whats-App-mage-2025-12-05-at-14-21-54.jpg',
    'La Liga': 'https://i.ibb.co/C55n1CFc/spain-la-liga-64x64-football-logos-cc.png',
    'Super Lig': 'https://i.ibb.co/RT40RH3G/turkey-super-lig-64x64-football-logos-cc.png',
    'Bundesliga': 'https://i.ibb.co/fzrPDNQp/germany-bundesliga-64x64-football-logos-cc.png',
    'Ligue 1': 'https://i.ibb.co/cXSXDS45/france-ligue-1-64x64-football-logos-cc.png'
};

export const calculatePercentage = (home, away) => {
    if (!home || !away) return 0;
    const total = parseFloat(home) + parseFloat(away);
    return Math.round((parseFloat(home) / total) * 100);
};

export const getLeagueLogo = (leagueName) => {
    return LEAGUE_LOGOS[leagueName] || 'https://i.ibb.co/RT40RH3G/turkey-super-lig-64x64-football-logos-cc.png';
};
